apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name -}}-busybox
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-90"
  labels:
    chartName: {{ .Chart.Name }}
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 10']
      restartPolicy: OnFailure
    # The pod template ends here